pub mod composite_types;
pub mod data;
pub mod decision;
pub mod enum_type;
pub mod functions;
pub mod loops;
pub mod ownership;
pub mod primitive_types;
pub mod struct_type;
pub mod borrowing;

pub use composite_types::default_function as composite_types;
pub use data::default_function as data;
pub use decision::default_function as decision;
pub use enum_type::default_function as enum_type;
pub use functions::default_function as functions;
pub use loops::default_function as loops;
pub use ownership::default_function as ownership;
pub use primitive_types::default_function as primitive_types;
pub use struct_type::default_function as struct_type;
pub use borrowing::default_function as borrowing;
